"""Add current_count to ScanLine

Revision ID: 09da22d96f6f
Revises: 488a7f2279bd
Create Date: 2025-10-09 09:23:57.813577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09da22d96f6f'
down_revision = '488a7f2279bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_lines', schema=None) as batch_op:
        batch_op.drop_column('current_count')

    # ### end Alembic commands ###
