"""Add line_code to ScanLine

Revision ID: 488a7f2279bd
Revises: 
Create Date: 2025-10-08 17:46:35.682245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488a7f2279bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_code', sa.String(length=100), nullable=False))
        batch_op.create_index(batch_op.f('ix_scan_lines_line_code'), ['line_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_lines_line_code'))
        batch_op.drop_column('line_code')

    # ### end Alembic commands ###
