"""Add sticker_type and dispatch_status field to ScanRecord

Revision ID: 67d8287b72bb
Revises: 
Create Date: 2025-10-31 17:01:48.258476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d8287b72bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sticker_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dispatch_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.drop_column('dispatch_status')
        batch_op.drop_column('sticker_type')

    # ### end Alembic commands ###
