"""Add barcode_entry table with unique barcode index

Revision ID: a84d9b454918
Revises: c10e77a1e738
Create Date: 2025-10-09 13:53:53.622021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84d9b454918'
down_revision = 'c10e77a1e738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barcode_entry', schema=None) as batch_op:
        batch_op.create_index('idx_barcode_unique', ['barcode'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barcode_entry', schema=None) as batch_op:
        batch_op.drop_index('idx_barcode_unique')

    # ### end Alembic commands ###
