"""Add is_locked and remarks to ScanLine

Revision ID: c10e77a1e738
Revises: 09da22d96f6f
Create Date: 2025-10-09 10:13:38.629282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10e77a1e738'
down_revision = '09da22d96f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_lines', schema=None) as batch_op:
        batch_op.drop_column('remarks')
        batch_op.drop_column('is_locked')

    # ### end Alembic commands ###
