"""Add quantity field to ScanRecord

Revision ID: e1939d282e2e
Revises: 2e23b49a610f
Create Date: 2025-10-30 17:48:02.459857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1939d282e2e'
down_revision = '2e23b49a610f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_records', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
